version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/cms"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/cms-backup"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/files"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/sleep"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"